---
# tasks file for install_package_font

- name: "{{ font_name }} · Check if font exists"
  ansible.builtin.shell:
    cmd: "fc-list | grep -q '{{ font_name }}'"
  register: check_font_result
  failed_when: check_font_result.rc > 1
  changed_when: check_font_result.rc == 1

- name: "{{ font_name }} · Create font dir in {{ font_dest }}"
  ansible.builtin.file:
    path: "{{ font_dest }}/{{ font_name }}"
    state: directory
    mode: 0755
  when: check_font_result.rc == 1

- name: "{{ font_name }} · Install nerd font"
  ansible.builtin.unarchive:
    src: "{{ font_url }}"
    dest: "{{ font_dest }}/{{ font_name }}"
    remote_src: true
    mode: 0644
  timeout: 300
  when: check_font_result.rc == 1
