---
# tasks file for install_package_git

- name: "{{ git_name }} · Clone the repository"
  ansible.builtin.git:
    repo: "{{ git_url }}"
    dest: "{{ ansible_env.HOME }}/{{ git_dest }}"
    version: "{{ git_version }}"
